# Generated by Django 2.2.6 on 2019-11-02 07:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyCountry',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('iso_country_code', models.CharField(max_length=5)),
                ('world_bank_country_code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtsyShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uri', models.CharField(default='', max_length=200)),
                ('etsy_id', models.IntegerField(blank=True, default=0)),
                ('oauth_token', models.CharField(blank=True, default='', max_length=200)),
                ('oauth_token_secret', models.CharField(blank=True, default='', max_length=200)),
                ('verifier', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EtsyListing',
            fields=[
                ('listing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('etsy_user_id', models.IntegerField(blank=True, default=0)),
                ('category_id', models.IntegerField(blank=True, default=0)),
                ('creation_tsz', models.IntegerField(blank=True, default=0)),
                ('ending_tsz', models.IntegerField(blank=True, default=0)),
                ('original_creation_tsz', models.IntegerField(blank=True, default=0)),
                ('last_modified_tsz', models.IntegerField(blank=True, default=0)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('currency_code', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('sku', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('category_path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('category_path_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, size=None)),
                ('materials', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('shop_section_id', models.IntegerField(blank=True, default=0)),
                ('featured_rank', models.IntegerField(blank=True, default=0)),
                ('state_tsz', models.IntegerField(blank=True, default=0)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('shipping_template_id', models.IntegerField(blank=True, default=0)),
                ('processing_min', models.IntegerField(blank=True, default=0)),
                ('processing_max', models.IntegerField(blank=True, default=0)),
                ('who_made', models.CharField(blank=True, max_length=200)),
                ('is_supply', models.CharField(blank=True, max_length=200)),
                ('when_made', models.CharField(blank=True, max_length=200)),
                ('item_weight', models.CharField(blank=True, max_length=200)),
                ('item_weight_unit', models.CharField(blank=True, max_length=200)),
                ('item_length', models.CharField(blank=True, max_length=200)),
                ('item_width', models.CharField(blank=True, max_length=200)),
                ('item_height', models.CharField(blank=True, max_length=200)),
                ('item_dimensions_unit', models.CharField(blank=True, max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('occasion', models.CharField(blank=True, max_length=200)),
                ('style', models.CharField(blank=True, max_length=200)),
                ('non_taxable', models.BooleanField(default=False)),
                ('is_customizable', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=False)),
                ('file_data', models.TextField(blank=True)),
                ('can_write_inventory', models.BooleanField(default=False)),
                ('should_auto_renew', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('has_variations', models.BooleanField(default=False)),
                ('taxonomy_id', models.IntegerField(blank=True, default=0)),
                ('taxonomy_path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('used_manufacturer', models.BooleanField(default=False)),
                ('is_vintage', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man.EtsyShop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
