# Generated by Django 2.2.6 on 2019-11-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_auto_20191102_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='creation_tsz',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='ending_tsz',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='last_modified_tsz',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='original_creation_tsz',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='state_tsz',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
