# Generated by Django 2.2.6 on 2019-11-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0003_auto_20191103_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='featured_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
