# Generated by Django 2.2.6 on 2019-11-03 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0004_auto_20191103_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='is_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='item_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='item_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='item_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='item_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='num_favorers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='processing_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='processing_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='shipping_template_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='shop_section_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='style',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='taxonomy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
