# Generated by Django 2.2.6 on 2019-11-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0006_auto_20191103_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='occasion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
