# Generated by Django 2.2.6 on 2019-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0008_auto_20191109_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='shipping_template_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
