# Generated by Django 2.2.6 on 2019-11-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0010_etsyshop_jobs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsylisting',
            name='is_modified_locally',
            field=models.BooleanField(default=False),
        ),
    ]
