# Generated by Django 2.2.6 on 2019-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0011_etsylisting_is_modified_locally'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsylisting',
            name='jobs_log',
            field=models.TextField(blank=True),
        ),
    ]
