# Generated by Django 2.2.6 on 2019-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0013_auto_20191109_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='etsyshop',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
