# Generated by Django 2.2.6 on 2019-11-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0014_auto_20191109_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsylisting',
            name='suggested_taxonomy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
