# Generated by Django 2.2.6 on 2019-11-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0016_auto_20191109_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='item_dimensions_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
