# Generated by Django 2.2.6 on 2019-11-09 23:00

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('man', '0017_auto_20191109_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyReceipt',
            fields=[
                ('title', models.CharField(blank=True, max_length=200)),
                ('jobs_log', models.TextField(blank=True)),
                ('receipt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('buyer_email', models.CharField(blank=True, max_length=200)),
                ('creation_tsz', models.FloatField(blank=True, default=0.0)),
                ('last_modified_tsz', models.FloatField(blank=True, default=0.0)),
                ('is_gift', models.BooleanField(default=False)),
                ('is_overdue', models.BooleanField(default=False)),
                ('was_paid', models.BooleanField(default=False)),
                ('was_shipped', models.BooleanField(default=False)),
                ('currency_code', models.CharField(blank=True, max_length=20)),
                ('discount_amt', models.CharField(blank=True, max_length=20)),
                ('grandtotal', models.CharField(blank=True, max_length=20)),
                ('adjusted_grandtotal', models.CharField(blank=True, max_length=20)),
                ('buyer_adjusted_grandtotal', models.CharField(blank=True, max_length=20)),
                ('receipt_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man.EtsyShop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
