# Generated by Django 2.2.6 on 2019-11-10 00:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('man', '0018_etsyreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyTransaction',
            fields=[
                ('title', models.CharField(blank=True, max_length=200)),
                ('jobs_log', models.TextField(blank=True)),
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('receipt_id', models.IntegerField()),
                ('listing_id', models.IntegerField()),
                ('seller_user_id', models.IntegerField()),
                ('buyer_user_id', models.IntegerField()),
                ('creation_tsz', models.FloatField(blank=True, default=0.0)),
                ('paid_tsz', models.FloatField(blank=True, default=0.0)),
                ('shipped_tsz', models.FloatField(blank=True, default=0.0)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('currency_code', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('shipping_cost', models.CharField(blank=True, max_length=200)),
                ('transaction_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man.EtsyShop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
