# Generated by Django 2.2.10 on 2020-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0021_auto_20191112_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='category_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
