# Generated by Django 2.2.10 on 2020-03-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprocessstep',
            options={'ordering': ['step']},
        ),
    ]
