"""
Django settings for Zen-Commerce project.

Generated by 'django-admin startproject' using Django 2.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

import os

import django_heroku

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# https://www.etsy.com/developers/documentation/getting_started/oauth
# default here is localhost
OAUTH_CALLBACK_URI = "http://127.0.0.1:8000/man/oauth_callback"

ETSY_API_URI = "https://openapi.etsy.com/v2/"

ETSY_KEYSTRING = ''
ETSY_SHARED_SECRET = ''

# ETSY_SCOPES = ['listings_r', 'listings_w', 'listings_d', 'transactions_r', 'shops_rw']
ETSY_SCOPES = ["email_r","listings_r","listings_w","listings_d","transactions_r","transactions_w","billing_r","profile_r","profile_w","address_r","address_w","favorites_rw","shops_rw","cart_rw","recommend_rw","feedback_r","treasury_r","treasury_w"]

ALLOWED_HOSTS = ['*']

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2tqv223i0!t0&^5&cv*2k9y=mnjj^+ayw+&5vwyl&5ig*2pw2w'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',

    "django_rq",

    # Project specific apps
    'man',
    'flow',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zencommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zencommerce.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Django RQ
RQ_QUEUES = {
    'high': {
        'URL': os.getenv('REDISTOGO_URL', 'redis://localhost:6379'),
        'DEFAULT_TIMEOUT': 500,
    },
    'default': {
        'URL': os.getenv('REDISTOGO_URL', 'redis://localhost:6379'),
        'DEFAULT_TIMEOUT': 360,
    },
    'low': {
        'URL': os.getenv('REDISTOGO_URL', 'redis://localhost:6379'),
        'DEFAULT_TIMEOUT': 360,
    }
}

RQ_SHOW_ADMIN_LINK = True

# We use Sentry to track errors https://sentry.io

SENTRY_DSN = ''

# In 'local_settings.py' defined a SENTRY_DSN value.
# If you would like to activate Sentry - Sign up on Sentry.io and get your DSN

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'zencommerce',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

PER_PAGE = 10

# Local dev settings
try:
    # To use your own dev settings, create a file named 'local_settings.py'
    # in a same directory this file (settings.py) located
    #
    # It is good idea to put in local_settings:
    # OAUTH_CALLBACK_URI = "http://YOURDOMAIN/man/oauth_callback"
    # ETSY_KEYSTRING = 'KEYSTRING'
    # ETSY_SHARED_SECRET = 'SECRET'
    # SECRET_KEY = 'YOUR UNIQUE DJANGO SECRET KEY'
    # SENTRY_DSN = 'https://BLABLABLA@sentry.io/BLABLABLA'
    #
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.postgresql',
    #         'NAME': 'zencommerce',
    #         'USER': 'postgres',
    #         'PASSWORD': 'postgres',
    #         'HOST': '127.0.0.1',
    #         'PORT': '5432',
    #     }
    # }
    from .local_settings import *
except ImportError:
    pass

# Sentry.io
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()]
    )

# Heroku helper
django_heroku.settings(locals())
